### PR TITLE
feat: bring under ownership of cloudelements org

### PR DESCRIPTION
**Pull request by rockymadden**

### CODE REVIEW

**Comment by rockymadden** [comment]
Whoops, my bad.

**Comment by darrenmothersele** [comment]
Hey, what's this PR for? Let me know if I can help with anything. Cheers

**Comment by rockymadden** [comment]
No worries. Just forking off this fabulous fork :)

**Comment by darrenmothersele** [comment]
Feels a bit disingenuous.

**Comment by rockymadden** [comment]
Mmmkay. Welcome to open source!

**Comment by darrenmothersele** [comment]
That's not the open source world I inhabit. My open source world is about cooperation, collaboration, and collectively building things for the common good. I'm not sure what world you inhabit?

**Comment by rockymadden** [comment]
Totally. Please see: https://github.com/daz-is/jmespath.js/tree/publish#fork

When projects are dead or otherwise not maintained, you often fork. When those forks might also be dead, not follow the spirit of the original, you want to take the project in a new direction that the fork might not want, etc -- you can fork again to reduce risk. 

May the best fork win, with those same ideals. Maybe one will end up as the successor. Maybe one won't.

**Comment by darrenmothersele** [comment]
That's interesting. What are your feelings on attribution?

**Pull request closed without merging**
